---
title: "Book reviews"
aliases:
  - /reviews/
---

# Book reviews

Below is a collection of book reviews that I have posted - click the links to go to the full review.

1.  Adam Alter's [Irresistible: Why We Can't Stop Checking, Scrolling, Clicking and Watching](posts/alters-irresistible-why-we-cant-stop-checking-scrolling-clicking-and-watching.md): a well-written and entertaining book about a subject I don’t know much about (addiction), with one glaring slip.

1.  Dan Ariely’s  [The Honest Truth About Dishonesty: How We Lie to Everyone – Especially Ourselves](posts/arielys-the-honest-truth-about-dishonesty.md): Interesting substance as draws on Ariely's own work, but sometimes meanders. Will the results stand the test of time? [That question has since been answered - not well at all. For example, see [here](posts/does-a-moral-reminder-decrease-cheating.md) and [here](posts/a-default-of-disbelief.md).]

1.  Dan Ariely’s [Payoff: The Hidden Logic That Shapes Our Motivations](posts/dan-arielys-payoff-the-hidden-logic-that-shapes-our-motivations.md): Enjoyable, but not particularly deep read, with most of the results covered in [The Upside of Irrationality](posts/arielys-upside-irrationality.md).

1.  Dan Ariely's [Predictably Irrational](posts/arielys-predictably-irrational.md): Not a bad book for a sample of behavioural economics if you are new to the area.

1.  Dan Ariely's [The Upside of Irrationality](posts/arielys-upside-irrationality.md): Some interesting ideas (particularly early in the book) but seems light compared to Predictably Irrational.

1.  Roy Baumeister and John Tierney’s [Willpower: Rediscovery Our Greatest Strength](posts/baumeister-and-tierneys-willpower-rediscovering-the-greatest-human-strength.md): The book tended into the pop science/self-help genre and there was rarely enough depth to add anything to the current debates.

1.  Eric Beinhocker's [Origin of Wealth: Evolution, Complexity, and the Radical Remaking of Economics](posts/beinhockers-the-origin-of-wealth.md): The best readable discussion of the field of "evolutionary economics" and the application of complexity theory to economics.

1.  Shlomo Benartzi (and Jonah Lehrer’s) [The Smarter Screen: Surprising Ways to Influence and Improve Online Behaviour](posts/benartzi-and-lehrers-the-smarter-screen-surprising-ways-to-influence-and-improve-online-behaviour.md): Makes some interesting points and directed me to plenty of interesting material elsewhere. Just don't bet your house on the parade of results being replicable.

1.  Sam Bowles and Herb Gintis's [A Cooperative Species: Human Reciprocity and Its Evolution](posts/bowles-and-gintiss-a-cooperative-species.md): An interesting but unsatisfactory argument for the role of group selection in the emergence of cooperation.

1.  Robert Boyd and Peter Richerson's [The Origin and Evolution of Cultures](posts/boyd-and-richersons-the-origin-and-evolution-of-cultures.md): A seminal work on cultural evolution.

2.  Rob Brooks’s [Sex, Genes & Rock ‘n’ Roll: How evolution has shaped the modern world](posts/brookss-sex-genes-rock-n-roll.md): Obesity, population control, infanticide and rock ‘n’ roll from an evolutionary perspective.

1.  Janet Browne’s [Charles Darwin: Voyaging](posts/janet-brownes-charles-darwin-voyaging.md): The first part to the best Charles Darwin biography.

1.  Susan Cain's [Quiet: The Power of Introverts in a World That Can't Stop Talking](posts/susan-cains-quiet-the-power-of-introverts-in-a-world-that-cant-stop-talking.md): An important point that many of our environments, social structures and workplaces are unsuited to "introverts", but falls into a degree of cheer-leading and evidence-free story-telling.

2.  Bryan Caplan's [Selfish Reasons to Have More Kids](posts/caplans-selfish-reasons-to-have-more-kids.md): Parents can relax as there is not much they can do to change their children. And since they're easier than you think, why don't you have more?

2. Nick Chater's [The Mind is Flat: The Illusion of Mental Depth and the Improvised Mind](posts/nick-chaters-the-mind-is-flat-the-illusion-of-mental-depth-and-the-improvised-mind.md): A great book arguing that our minds have no hidden depth, with which I have one major fundamental disagreement.

3.  Brian Christian and Tom Griffiths's [Algorithms to Live By: The Computer Science of Human Decisions](posts/christian-and-griffithss-algorithms-to-live-by-the-computer-science-of-human-decisions.md): A nice contrast to the competition between perfectly rational decision makers and biased humans. Christian and Griffiths's decision-making benchmarks are the algorithms developed by mathematicians and computer scientists, with decision making under uncertainty involving trade-offs between efficiency, accuracy and the types of errors you are willing to accept.

4.  Gregory Clark's [The Son Also Rises: Surnames and the History of Social Mobility](posts/the-genetic-basis-of-social-mobility.md): Social mobility is low across countries and time because there is a genetic component to social status.

5.  John Coates’s [The Hour Between Dog and Wolf: Risk Taking, Gut Feelings and the Biology of Boom and Bust](posts/the-biology-of-boom-and-bust.md): How our hormones affect decision making in finance - the idea that traders are rational calculating machines driven by their brains is torn apart.

6.  David Colander and Roland Kupers's [Complexity and the Art of Public Policy](posts/complexity-and-the-art-of-public-policy.md): An important way to think about policy, even though I'm not convinced by many of their proposed applications.

7.  Pedro Domingos's [The Master Algorithm: How the Quest for the Ultimate Learning Machine Will Remake Our World](posts/domingoss-the-master-algorithm-how-the-quest-for-the-ultimate-learning-machine-will-remake-our-world.md): Parts verge on techno-Panglossianism. The chapters on the various "tribes" of machine learning and learning without supervision, are excellent. And I simply don't have the knowledge to judge the value of Domingos's reports on his progress to the master algorithm.

8.  Benoit Dubreuil’s [Human Evolution and the Origins of Hierarchies](posts/dubreuils-human-evolution-and-the-origins-of-hierarchies.md): The emergence of modern hierarchies was driven by the cognitive changes associated with the behavioural modernisation of human

9.  Angela Duckworth’s [Grit: The Power of Passion and Perseverance](posts/angela-duckworths-grit-the-power-of-passion-and-perseverance.md): Conscientiousness rebadged? Interesting but ignores biology and the stories suggest survivorship bias.

10. Carol Dweck's [Mindset: Changing the Way You Think to Fulfil Your Potential](posts/carol-dwecks-mindset-changing-the-way-you-think-to-fulfil-your-potential.md)

10. Niall Ferguson’s [Civilization: The West and the Rest](posts/fergusons-civilization-the-west-and-the-rest.md): Entertaining and some interesting ideas. Those looking for a grand history of everything will be disappointed.

11. James Flynn's [Are We Getting Smarter?](posts/flynns-are-we-getting-smarter.md): A comprehensive update on the latest in IQ testing from around the globe, plus a few interesting arguments.

12. Robert Franks's [Passions Within Reason: The Strategic Role of the Emotions](posts/franks-passions-within-reason.md): A fantastic game theoretic approach to the role of the emotions.

13. Robert Frank's [Luxury Fever: Weighing the Cost of Excess](posts/franks-luxury-fever.md): People over-consume goods where there is competition for relative rank.

14. Robert Frank's [The Darwin Economy: Liberty, Competition, and the Common Good](posts/franks-the-darwin-economy.md): Many aspects of the economy are Darwinian, not Smithian.

15. Paul Frijters with Gigi Foster's [An Economic Theory of Greed, Love, Groups and Networks](posts/an-economic-theory-of-greed-love-groups-and-networks.md): An attempt to supplement mainstream economic arguments with a perspective on love, groups and networks. I don't buy into many of the arguments, but one of the most interesting books I have read.

16. Francis Fukuyama’s [The Origins of Political Order: From Prehuman Times to the French Revolution](posts/fukuyamas-the-origins-of-political-order.md): A grand history with self-interest as a motivating factor of the individual actor.

17. Arthur Gandolfi, Anna Sachko Gandolfi and David P. Barash's [Economics as an Evolutionary Science: From Utility to Fitness](posts/gandolfi-gandolfi-and-barashs-economics-as-an-evolutionary-science.md): The title captures the book's core focus on translating the economic concept of utility into the biological concept of fitness.

18. Oded Galor's [Unified Growth Theory](posts/galors-unified-growth-theory.md): A fine summary of the most serious attempt to accommodate human evolution into theories of economic growth. Highly technical and not an easy read.

19. Sheldon Garon’s [Beyond Our Means: Why America Spends While the World Saves](posts/garons-beyond-our-means.md): Plenty of interesting historical fodder on savings but feels incomplete.

20. Gerd Gigerenzer's [Gut Feelings: Short Cuts to Better Decision Making](posts/gerd-gigerenzers-gut-feelings-short-cuts-to-better-decision-making.md): Perhaps the best balance between nuance and accessibility of Gigerenzer's popular books. While it still leaves an impression about the accuracy of our instincts that I'm not completely in agreement with, it provides a good overview of how our gut feelings can lead togood decisions.

21. Gerd Gigerenzer's [Rationality for Mortals: How People Cope with Uncertainty](posts/gerd-gigerenzers-rationality-for-mortals-how-people-cope-with-uncertainty.md): Great. Good coverage of ecological rationality, heuristics that make us smart, and understanding risk.

22. Gerd Gigerenzer's [Risk Savvy](posts/nudging-citizens-to-be-risk-savvy.md): Gigerenzer's least satisfactory but still interesting book.

23. Gerd Gigerenzer, Peter Todd and the ABC Research Group's [Simple Heuristics That Make Us Smart](posts/simple-heuristics-that-make-us-smart.md): Excellent. A nice contrast to the increasing use of complex machine learning algorithms for decision making, although it is that same increasing use that makes some parts of the book are seem a touch dated.

24. Malcolm Gladwell’s [Outliers: The Story of Success](posts/gladwells-outliers.md): Like all of Gladwell's book - flawed but interesting.

25. Jonathan Gottschall's [The Storytelling Animal: How Stories Make Us Human](posts/gottschalls-the-storytelling-animal.md): Gottschall argues that storytelling is often deeply moral, normally deals with problems of great (evolutionary) relevance to us and is a major cohering force in society. I tend to agree.

26. Jonathan Haidt's [The Righteous Mind: Why Good People Are Divided by Politics and Religion](posts/haidts-the-righteous-mind.md): A brilliant analysis of why people are divided by politics and religion. Just don't buy his arguments on group selection.

27. Dan Hamermesh's [Beauty Pays: Why Attractive People Are More Successful](posts/hamermeshs-beauty-pays.md): Beauty has its benefits, but are the beautiful more productive?

28. Tim Harford's [Adapt: Why Success Always Starts with Failure](posts/harfords-adapt-why-success-always-starts-with-failure.md): Harford applies evolutionary thinking to business, war, accidents and other human pursuits. Excellent.

29. Joe Henrich’s [The Secret of Our Success: How Culture Is Driving Human Evolution, Domesticating Our Species, and Making Us Smarter](posts/henrichs-the-secret-of-our-success-how-culture-is-driving-human-evolution-domesticating-our-species-and-making-us-smarter.md): A lot of interesting ideas, but left me with a lot of questions.

30. Victor Hwang and Greg Horowitt’s [The Rainforest: The Secret to Building the Next Silicon Valley](posts/hwang-and-horowitts-the-rainforest.md): Entrepreneurship though a biological lens.

31. Greg Ip's [Foolproof: Why Safety Can Be Dangerous and How Danger Makes Us Safe](posts/ips-foolproof-why-safety-can-be-dangerous-and-how-danger-makes-us-safe.md): Engineers seek to use the sum of our human knowledge to make us safer. Ecologists recognise that many of our solutions will have unintended consequences that can be worse than the problems we are trying to solve. Much of Ip’s book is a catalogue of the failures of engineering.

32. Garett Jones’s [Hive Mind: How Your Nation’s IQ Matters So Much More Than Your Own](posts/joness-hive-mind-how-your-nations-iq-matters-so-much-more-than-your-own.md): A fantastic exposition of some important but neglected features of the world.

33. Daniel Kahneman's [Thinking, Fast and Slow](posts/kahnemans-thinking-fast-and-slow.md): Flawed but possibly the best overview of behavioural economics there is. However, it is [not standing the test of time particularly well](posts/re-reading-kahnemans-thinking-fast-and-slow.md).
    
34. Garry Kasparov's [Deep Thinking: Where Machine Intelligence Ends and Human Creativity Begins](posts/kasparovs-deep-thinking-where-machine-intelligence-ends-and-human-creativity-begins.md): More a history of man versus machine in chess than a deep analysis of human or machine intelligence.

35. Eric Kaufmann’s [Shall the Religious Inherit the Earth?: Demography and Politics in the Twenty-First Century](posts/kaufmanns-shall-the-religious-inherit-the-earth-demography-and-politics-in-the-twenty-first-century.md): Even if you assign a low probability to Kaufmann’s projections, it provides another strand to the case that low fertility in the secular West is not without costs.

36. John Kay’s [Other People’s Money](posts/kays-other-peoples-money.md): A generally excellent book arguing that the growth in the size of the financial system hasn’t been matched by improvements in the allocation of capital.

37. Kevin Kelly's [What Technology Wants](posts/kellys-what-technology-wants.md): Ignoring his near-religious fervour, Kelly provides a strong argument that the growth in technology is primarily beneficial.

38. Doug Kenrick and Vlad Griskevicius’s [The Rational Animal: How Evolution Made Us Smarter Than We Think](posts/kenrick-and-griskeviciuss-the-rational-animal.md): A good introduction to the idea that evolutionary psychology could add a lot of value to behavioural economics, but has the occasional straw man discussion of economics and a heavy reliance on priming research.

39. Gary Klein's [Sources of Power: How People Make Decisions](posts/gary-kleins-sources-of-power-how-people-make-decisions.md): An important book describing how many experts make decisions, but with a lingering question mark about how good these decisions actually are.

39. Jonathan Last’s [What to Expect When No One’s Expecting: America’s Coming Demographic Disaster](posts/lasts-what-to-expect-when-no-ones-expecting-americas-coming-demographic-disaster.md): Much to disagree or argue with, but entertaining and a lot to like.

40. David Levine’s [Is Behavioural Economics Doomed?](posts/levines-is-behavioural-economics-doomed.md): A good but slightly frustrating read. Littered with straw man arguments.

41. Michael Lewis’s [The Undoing Project: A Friendship That Changed The World](posts/michael-lewiss-the-undoing-project-a-friendship-that-changed-the-world.md): A layperson would struggle to find a more accessible and interesting introduction to behavioural science and behavioural economics.

42. Benoit Mandelbrot and Richard Hudson’s [The (mis)Behaviour of Markets: A Fractal View of Risk, Ruin, and Reward](posts/mandelbrot-and-hudsons-the-misbehaviour-of-markets-a-fractal-view-of-risk-ruin-and-reward.md): A clear critique of the underpinnings of modern financial theory.

43. Jim Manzi's [Uncontrolled: The Surprising Payoff of Trial-and-Error for Business, Politics, and Society](posts/manzis-uncontrolled.md): Excellent. The high “causal density” in social science settings nearly always results in the possibility that there is an important factor you have missed or do not understand. No matter what our worldview, we should be prepared to allow experimentation with alternatives, as we may well be wrong.

44. Joanna Masel’s [Bypass Wall Street: A Biologist’s Guide to the Rat Race](posts/masels-bypass-wall-street-a-biologists-guide-to-the-rat-race.md): Interesting, although would have benefited from more of a biological lens.

45. Michael Mauboussin’s [More Than You Know: Finding Financial Wisdom in Unconventional Places](posts/michael-mauboussins-more-than-you-know-finding-financial-wisdom-in-unconventional-places.md): We need an interdisciplinary toolkit to give us the diversity to make good decisions.

46. Michael Mauboussin’s [Think Twice: Harnessing the Power of Counterintuition](posts/michael-mauboussins-think-twice-harnessing-the-power-of-counterintuition.md): A multi-disciplinary book on how to improve your decision making. Not great depth, but interesting pointers to new ideas.

47. Geoffrey Miller's [Spent: Sex, Evolution, and Consumer Behavior](posts/millers-spent-sex-evolution-and-consumer-behavior.md): Evolution shaped our consumer preferences but they do not always work perfectly in a modern environment.

48. Ian Morris’s [Why the West Rules - for Now](posts/morriss-why-the-west-rules-for-now.md): History is made by lazy, greedy, frightened people (who rarely know what they’re doing) looking for easier, more profitable, and safer ways to do things.

49. Sendhil Mullainathan and Eldar Shafir’s [Scarcity: Why Having Too Little Means So Much](posts/scarcity-of-time-money-friends-and-bandwidth.md): A novel way of looking at scarcity that extends beyond the typical analysis in economics, but I’m not convinced I have been presented with a coherent new perspective on how the world works.

50. Richard Nelson and Sidney Winter's [An Evolutionary Theory of Economic Change](posts/nelson-and-winters-an-evolutionary-theory-of-economic-change.md): The seminal book that established evolutionary economics as a serious field.

51. Cal Newport’s [So Good They Can’t Ignore You: Why Skills Trump Passion in the Quest for Work You Love](posts/newports-so-good-they-cant-ignore-you-why-skills-trump-passion-in-the-quest-for-work-you-love.md): Basic (albeit good) economic advice dressed up in self-help style.

52. Cathy O'Neil's [Weapons of Math Destruction: How Big Data Increases Inequality and Threatens Democracy](posts/oneils-weapons-of-math-destruction-how-big-data-increases-inequality-and-threatens-democracy.md): O'Neil makes a strong and persuasive case that many algorithms could be developed or used better. But it is often unclear what exactly the problem is or what potential solutions could (should) be.

53. Paul Ormerod's [Why Most Things Fail](posts/ormerods-why-most-things-fail.md): Failure is all around us. But after building a great picture of the complexity of the world, the applications seem half-baked.

54. Charles Perrow’s [Normal Accidents: Living with High-Risk Technologies](posts/perrows-normal-accidents-living-with-high-risk-technologies.md): We should stop trying to fix systems prone to normal accidents in ways that only make them riskier. We should focus instead on reducing the potential for catastrophe when there is failure.

55. Paul Rubin's [Darwinian Politics: The Evolutionary Origin of Freedom](posts/rubins-darwinian-politics.md): Humans naturally seek political freedom and Modern Western societies do the best job of meeting these needs.

56. Phil Rosenzweig’s [Left Brain, Right Stuff: How Leaders Make Winning Decisions](posts/rosenzweigs-left-brain-right-stuff-how-leaders-make-winning-decisions.md): An entertaining examination of how behavioural economics findings hold up for real world decision making.

57. Phil Rosenzweig’s [The Halo Effect … and the Eight Other Business Delusions That Deceive Managers](posts/rosenzweigs-the-halo-effect-and-the-eight-other-business-delusions-that-deceive-managers.md): Largely an exercise of shooting fish in a barrel, but is an entertaining read regardless.

58. Gad Saad's [The Evolutionary Bases of Consumption](posts/saads-the-evolutionary-bases-of-consumption.md): This book has more material taking on the Standard Social Science Model approach to consumption than is fun to wade through, but Saad's book is still the go to source for material on the evolutionary psychology approach to consumption.
    
59. Gilles Saint-Paul's [The Tyranny of Utility: Behavioral Social Science and the Rise of Paternalism](posts/saint-pauls-the-tyranny-of-utility-behavioral-social-science-and-the-rise-of-paternalism.md): Sometimes hard to share Saint-Paul's anger, but some important underlying points.

60. Robert Sapolsky's [Why Zebra's Don't Get Ulcers](posts/robert-sapolskys-why-zebras-dont-get-ulcers.md): A wonderful book on the psychology and physiology of stress.

61. Barry Schwartz's [The Paradox of Choice: Why More Is Less](posts/barry-schwartzs-the-paradox-of-choice-why-more-is-less.md): An excellent diagnosis with a less than convincing proposal for treatment.

61. Paul Seabright's [The War of the Sexes: How Conflict and Cooperation Have Shaped Men and Women from Prehistory to the Present](posts/seabrights-the-war-of-the-sexes.md): A decent primer on sexual selection and some interesting applications, but does not always engage with the cutting edge of the debate.

62. Nate Silver’s [The Signal and the Noise: Why So Many Predictions Fail— but Some Don’t](posts/silvers-the-signal-and-the-noise.md): Not a “how to” book, although there are plenty of principles (and suggestions to be humble) worth following.

63. Robert Sugden's [The Community of Advantage: A Behavioural Economist’s Defence of the Market](posts/robert-sugdens-the-community-of-advantage-a-behavioural-economists-defence-of-the-market.md): A well-balanced critique on how the behavioural research has been interpreted and used as part of the “nudge” movement to develop recommendations for the “planner”, “benevolent autocrat” or “choice architect”.

64. Cass Sunstein and Reid Hastie's [Wiser: Getting Beyond Groupthink to Make Groups Smarter](posts/cass-sunstein-and-reid-hasties-wiser-getting-beyond-groupthink-to-make-groups-smarter.md): Not an exciting read, but a good catalogue of group decision-making research.

65. Philip Tetlock’s [Expert Political Judgment: How Good Is It? How Can We Know?](posts/tetlocks-expert-political-judgment-how-good-is-it-how-can-we-know.md): One of the grander undertakings in social science.

66. Philip Tetlock and Dan Gardner’s [Superforecasting: The Art and Science of Prediction](posts/tetlock-and-gardners-superforecasting-the-art-and-science-of-prediction.md): Doesn’t quite measure up to Tetlock’s superb [Expert Political Judgment](posts/tetlocks-expert-political-judgment-how-good-is-it-how-can-we-know.md) (read EPJ first), but it contains more than enough interesting material to make it worth the read.

67. Richard Thaler and Cass Sunstein’s [Nudge](posts/thaler-and-sunsteins-nudge.md): If you’re familiar with much of the behavioural science literature, the book covers a lot of stuff you already know. But there are a lot of bureaucrats and politicians who, among others, should read the whole book.

68. Peter Thiel’s [Zero to One: Notes on Startups, or How to Build the Future](posts/thiels-zero-to-one.md): Many interesting and contrary arguments, but this is not a book where they are buttressed with evidence to convince you they are true.

69. Robert Trivers's [The Folly of Fools: The Logic of Deceit and Self-Deception in Human Life](posts/triverss-the-folly-of-fools.md): Some gems surrounded by political rants.

70. Thorstein Veblen‘s [The Theory of the Leisure Class](posts/thorstein-veblens-the-theory-of-the-leisure-class.md): The classic on status and conspicuous consumption.

71. Chris Voss’s (with Tahl Raz) [Never Split the Difference: Negotiating as if your life depended on it](posts/chris-vosss-never-split-the-difference-negotiating-as-if-your-life-depended-on-it.md): Interesting ideas on how to approach negotiation, but I don’t know how much weight to give them. How much expertise could be developed in hostage negotiations? Can that expertise be distilled into principles, or is much of it tacit knowledge?

72. E.O. Wilson's [The Social Conquest of Earth](posts/e-o-wilsons-the-social-conquest-of-earth.md): A confusing take on kin and group selection.

73. Philip Zimbardo’s [The Lucifer Effect: Understanding How Good People Turn Evil](posts/zimbardos-the-lucifer-effect.md): The situation is more important than a person’s disposition.